# Generated by Django 3.2 on 2021-06-08 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_visits', models.IntegerField(default=0)),
                ('viewed_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
