# Generated by Django 3.2 on 2021-06-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SiteVisits',
        ),
    ]
